README.md, src/main/java/com/getindata/connectors/http/sink/HttpSinkWriter.java, src/test/java/com/getindata/connectors/http/sink/HttpSinkConnectionTest.java
=> Disable retries of failed requests

CHANGELOG.md, README.md, src/main/java/com/getindata/connectors/http/internal/SinkHttpClient.java, src/main/java/com/getindata/connectors/http/internal/config/HttpConnectorConfigConstants.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupConfig.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClient.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientFactory.java, src/main/java/com/getindata/connectors/http/internal/table/sink/HttpDynamicTableSinkFactory.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceITCaseTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientFactoryTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientITCaseTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientTest.java
Signed-off-by: Krzysztof Chmielewski <krzysztof.chmielewski@getindata.com>
Add Http header support for Http Lookup Source.
=> ESP-119_Http_headers_SourceSupport - Add Http header support for Http Lookup Source.

CHANGELOG.md, README.md, src/main/java/com/getindata/connectors/http/HttpSink.java, src/main/java/com/getindata/connectors/http/HttpSinkBuilder.java, src/main/java/com/getindata/connectors/http/internal/BasicAuthHeaderValuePreprocessor.java, src/main/java/com/getindata/connectors/http/internal/ComposeHeaderPreprocessor.java, src/main/java/com/getindata/connectors/http/internal/HeaderPreprocessor.java, src/main/java/com/getindata/connectors/http/internal/HeaderValuePreprocessor.java, src/main/java/com/getindata/connectors/http/internal/SinkHttpClientBuilder.java, src/main/java/com/getindata/connectors/http/internal/sink/HttpSinkInternal.java, src/main/java/com/getindata/connectors/http/internal/sink/httpclient/JavaNetSinkHttpClient.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClient.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientFactory.java, src/main/java/com/getindata/connectors/http/internal/table/sink/HttpDynamicSink.java, src/main/java/com/getindata/connectors/http/internal/table/sink/Slf4jHttpPostRequestCallback.java, src/main/java/com/getindata/connectors/http/internal/utils/ConfigUtils.java, src/main/java/com/getindata/connectors/http/internal/utils/HttpHeaderUtils.java, src/test/java/com/getindata/connectors/http/internal/BasicAuthHeaderValuePreprocessorTest.java, src/test/java/com/getindata/connectors/http/internal/HttpsConnectionTestBase.java, src/test/java/com/getindata/connectors/http/internal/sink/HttpSinkBuilderTest.java, src/test/java/com/getindata/connectors/http/internal/sink/httpclient/JavaNetSinkHttpClientConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/sink/httpclient/JavaNetSinkHttpClientTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientHttpsConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientTest.java, src/test/java/com/getindata/connectors/http/internal/utils/ConfigUtilsTest.java
Signed-off-by: Krzysztof Chmielewski <krzysztof.chmielewski@getindata.com>
Add Http Header value preprocessor mechanism, that can preprocess defined header value before setting it on the request.
It allows user to specify `Autorization` header for Basic Authentication. The value will be converted to Base64,
or it will be used is if the valued is starting from `Basic ` prefix.
=> ESP-221_BasicAuth - adding HeaderPreprocessor and support for Basic Authentication mechanism.

CHANGELOG.md, README.md, src/main/java/com/getindata/connectors/http/LookupArg.java, src/main/java/com/getindata/connectors/http/LookupQueryCreator.java, src/main/java/com/getindata/connectors/http/LookupQueryCreatorFactory.java, src/main/java/com/getindata/connectors/http/internal/PollingClient.java, src/main/java/com/getindata/connectors/http/internal/PollingClientFactory.java, src/main/java/com/getindata/connectors/http/internal/config/HttpConnectorConfigConstants.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupConnectorOptions.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSource.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpTableLookupFunction.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClient.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/ElasticSearchLiteQueryCreator.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/ElasticSearchLiteQueryCreatorFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericGetQueryCreator.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericGetQueryCreatorFactory.java, src/main/java/com/getindata/connectors/http/internal/utils/uri/NameValuePair.java, src/main/java/com/getindata/connectors/http/internal/utils/uri/URLEncodedUtils.java, src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, src/test/java/com/getindata/connectors/http/internal/ComposeHeaderPreprocessorTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/HttpRowDataLookupFunctionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientFactoryTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientHttpsConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/querycreators/ElasticSearchLiteQueryCreatorTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericGetQueryCreatorTest.java, src/test/java/com/getindata/connectors/http/internal/utils/uri/URIBuilderTest.java
- Add [LookupQueryCreator](src/main/java/com/getindata/connectors/http/LookupQueryCreator.java) and [LookupQueryCreatorFactory](src/main/java/com/getindata/connectors/http/LookupQueryCreatorFactory.java) interfaces (along with a "default" [GenericGetQueryCreator](src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericGetQueryCreator.java) implementation) for customization of queries prepared by Lookup Source for its HTTP requests.
- Add [ElasticSearchLiteQueryCreator](src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/ElasticSearchLiteQueryCreator.java) that prepares [`q` parameter query](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-api-query-params-q) using Lucene query string syntax …
=> Adapt Http Lookup Source to Elastic

CHANGELOG.md, README.md, src/main/java/com/getindata/connectors/http/LookupQueryCreator.java, src/main/java/com/getindata/connectors/http/LookupQueryCreatorFactory.java, src/main/java/com/getindata/connectors/http/internal/PollingClientFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/BodyBasedRequestFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/GetRequestFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupConnectorOptions.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSource.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpRequestFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpTableLookupFunction.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClient.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/RequestFactoryBase.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/ElasticSearchLiteQueryCreatorFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericGetQueryCreator.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericJsonQueryCreator.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericJsonQueryCreatorFactory.java, src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, src/test/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceITCaseTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/HttpRowDataLookupFunctionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientFactoryTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientHttpsConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientTest.java
Adding support for using POST REST request method to http Lookup Source. In fact any method HTTP method can be used.
Request method can be set by using DDL option `lookup-method` with value "GET", "POST" etc. If option is not defined, then GET method will be used.
For request body methods like POST/PUT lookup parameters will be converted to json and used as request body.
For default configuration the new `LookupQueryCreator` interface implementation - `GenericJsonQueryCreator` will be used to convert Join arruments to json, for example
```
{
"id": "1",
"uuid": "2"
}
```
User can define custom `LookupQueryCreator` and use it for its table definition via `gid.connector.http.source.lookup.query-creator` property
=> ESP-263 - Adding suport for POST REST method to http Lookup Source

CHANGELOG.md, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSource.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceFactory.java
The 'HttpLookupTableSource' has unused reference to Encoding format. It is not needed, since concrete type of encoding format should be created by 'LookupQueryCreatorFactory' implementation.
This PR removes this reference.
Resolves https://github.com/getindata/flink-http-connector/issues/43
=> [HTTP-43] - Remove Encoding format from HttpLookupTableSource

CHANGELOG.md, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupSourceRequestEntry.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpRequestFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClient.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/RequestFactoryBase.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/Slf4JHttpLookupPostRequestCallback.java
The Slf4JHttpLookupPostRequestCallback is an implementation of HttpPostRequestCallback interface for auditing http lookup queries and responses.
It turns out that Slf4JHttpLookupPostRequestCallback implementation does not print HttpReqeust body (json body or GET parameters).
This PR adds new object wrapper, HttpLookupSourceRequestEntry, that wraps original Java 11 HttpRequest and an actual request body or GET parameters.
Resolves https://github.com/getindata/flink-http-connector/issues/45
=> [HTTP-45] - Fix issue with not printing HttpRequest body/parameters for Lookup Source by Slf4JHttpLookupPostRequestCallback.

.github/workflows/build.yml, CHANGELOG.md, pom.xml, src/main/java/com/getindata/connectors/http/HttpSinkBuilder.java, src/main/java/com/getindata/connectors/http/SchemaLifecycleAwareElementConverter.java, src/main/java/com/getindata/connectors/http/internal/sink/HttpSinkInternal.java, src/main/java/com/getindata/connectors/http/internal/table/SerializationSchemaElementConverter.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpTableLookupFunction.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericJsonQueryCreator.java, src/main/java/com/getindata/connectors/http/internal/table/sink/HttpDynamicSink.java, src/main/java/com/getindata/connectors/http/internal/utils/SerializationSchemaUtils.java, src/test/java/com/getindata/connectors/http/internal/sink/HttpSinkWriterTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientHttpsConnectionTest.java
It was not possible to use HTTP connector with Flink 1.16. This PR allows to use HTTP connector with Flink 1.15 and 1.16. 
Additionally extra GitHub builds were added to make sure our connector can be used with different Flink versions.
The https://issues.apache.org/jira/browse/FLINK-28807 introduced in Flink 1.16 changed the way how `SerializationSchema` and `DeserializationSchema` objects should be initialized. The change that impacted HTTP connector was change made in Flink's `JsonRowDataSerializationSchema`. Before FLINK-28807 `ObjectMapper` instance for `JsonRowDataSerializationSchema` was initialized as class field member, where in Flink 1.16 ObjecTMaper is initialized in `open` method which we did not call.
Proposed change simply ensure that `open` method will be called for every …
=> [HTTP-37] - Add support for Flink 1.16.

CHANGELOG.md, src/main/java/com/getindata/connectors/http/LookupQueryCreator.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/BodyBasedRequestFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/GetRequestFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupSourceRequestEntry.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/LookupQueryInfo.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/RequestFactoryBase.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/Slf4JHttpLookupPostRequestCallback.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/ElasticSearchLiteQueryCreator.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericGetQueryCreator.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericJsonQueryCreator.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/LookupQueryInfoTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/querycreators/ElasticSearchLiteQueryCreatorTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericGetQueryCreatorTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericJsonQueryCreatorTest.java
Support for optional query parameters for body-based requests
As [documented](https://github.com/getindata/flink-http-connector/blob/main/README.md#http-tablelookup-source), the connector currently create a lookup query from the HTTP TableLookup Source to build either:
- a query parameter list in case of a HTTP GET request
- a body payload in case of a HTTP body-based request
There is no way to change this behaviour with custom factories.
Modification:
- Change the signature of createLookupQuery(RowData lookupDataRow) in interface `LookupQueryCreator` so that it returns a class `LookupQueryInfo` holding:
- the lookup query
- the optional body-based query parameters
- Adapt the creation of the URIs in the constructions of HTTP requests to retrieve information from the class …
=> HTTP-78 Support for optional query parameters for body-based requests

.github/workflows/build.yml, CHANGELOG.md, pom.xml, src/test/java/com/getindata/connectors/http/internal/sink/HttpSinkConnectionTest.java
Add junit 5 support - so tests can run against Flink 1.17 and 1.18 
Resolves #64
=> issue 64 add junit 5 support

CHANGELOG.md, src/main/java/com/getindata/connectors/http/internal/table/lookup/BodyBasedRequestFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/GetRequestFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/LookupQueryInfo.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/RequestFactoryBase.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/BodyBasedRequestFactoryTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/LookupQueryInfoTest.java
add path patameter support
Resolves #74
=> HTTP-74 Add path parameter support

CHANGELOG.md, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSource.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceITCaseTest.java
Ability to support SQL queries that add or remove columns on the result of a lookup join query.
Resolves #83
=> HTTP-83 Support SQL queries with project pushdown after a lookup join

CHANGELOG.md, README.md, src/main/java/com/getindata/connectors/http/HttpPostRequestCallbackFactory.java, src/main/java/com/getindata/connectors/http/internal/config/HttpConnectorConfigConstants.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupConfig.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupConnectorOptions.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClient.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/Slf4JHttpLookupPostRequestCallback.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/Slf4jHttpLookupPostRequestCallbackFactory.java, src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, src/test/java/com/getindata/connectors/http/HttpPostRequestCallbackFactoryTest.java, src/test/java/com/getindata/connectors/http/TestLookupPostRequestCallbackFactory.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientHttpsConnectionTest.java, src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory
Ability to override the default SLF4J logger for used for HTTP source lookup.
Resolves #92
=> HTTP-92 Customization of HTTP lookup source logger

CHANGELOG.md, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClient.java
Resolves [#96](https://github.com/getindata/flink-http-connector/issues/96).
---
As there are no tests specifically for the logs, the validation of the PR is done manually as follows:
1. Set the DEBUG level in https://github.com/getindata/flink-http-connector/blob/main/src/test/resources/log4j2-test.properties#L19
2. `mvn clean test -Dtest=JavaNetHttpPollingClientConnectionTest`
=> the log contains:
```
Received status code [201] for RestTableSource request with Server response body [{
"id": "COUNTER", [...] ]
```
Without the fix, it is:
```
Received status code [%s] for RestTableSource request with Server response body [%s]
```
=> HTTP-96 Fix logging code in JavaNetHttpPollingClient

CHANGELOG.md, README.md, pom.xml, src/main/java/com/getindata/connectors/http/HttpSinkBuilder.java, src/main/java/com/getindata/connectors/http/internal/OIDCAuthHeaderValuePreprocessor.java, src/main/java/com/getindata/connectors/http/internal/auth/OidcAccessTokenManager.java, src/main/java/com/getindata/connectors/http/internal/config/HttpConnectorConfigConstants.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupConnectorOptions.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSource.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceFactory.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/HttpTableLookupFunction.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/RequestFactoryBase.java, src/main/java/com/getindata/connectors/http/internal/table/sink/HttpDynamicSink.java, src/main/java/com/getindata/connectors/http/internal/utils/HttpHeaderUtils.java, src/test/java/com/getindata/connectors/http/internal/HttpsConnectionTestBase.java, src/test/java/com/getindata/connectors/http/internal/auth/OidcAccessTokenManagerTest.java, src/test/java/com/getindata/connectors/http/internal/sink/httpclient/JavaNetSinkHttpClientTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/HttpLookupTableSourceFactoryTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientHttpsConnectionTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientTest.java
Add support for bearer tokens. 
Resolves `HTTP91`
- [x ] Tests added
- [x ] [Changelog](CHANGELOG.md) updated
=> http91 bearer token support

.github/workflows/build.yml, pom.xml
Step "Add coverage to PR" fails with the following error:
```
Error: ENOENT: no such file or directory, open '/home/runner/work/flink-http-connector/flink-http-connector/target/site/jacoco/jacoco.xml'
```
Adding `${argLine}` as below solves the issue.
```
<argLine>${argLine} ...</argLine>
```
=> Fix adding coverage to PRs

CHANGELOG.md, src/main/java/com/getindata/connectors/http/internal/table/lookup/querycreators/GenericJsonQueryCreatorFactory.java, src/main/java/com/getindata/connectors/http/internal/utils/SynchronizedSerializationSchema.java
Async lookup queries may return incorrect results because `org.apache.flink.formats.json.JsonRowDataSerializationSchema` is not thread-safe. In this PR I introduce a temporary fix, which ensures that SerializationSchema is used in thread-safe way. In long-term we should refactor the code so that serialization can be safely run in parallel.
Resolves `HTTP-121`.
=> HTTP-121 Ensure SerializationSchema is used in thread-safe way

CHANGELOG.md, README.md, src/main/java/com/getindata/connectors/http/internal/utils/JavaNetHttpClientFactory.java
use default certs when no security configured for https
Resolves `HTTP119`
=> HTTP-119 use default certs when no security configured for https

.gitignore, CHANGELOG.md
HTTP138 ignore Eclipse files in .gitignore
Resolves `HTTP138`
- [n/a] Tests added
=> HTTP138 ignore Eclipse files in .gitignore

.github/workflows/build.yml, CHANGELOG.md, README.md, pom.xml
Support Flink 1.20. Bumping up the level at which we build from Flink 1.16 to 1.18
Resolves `HTTP103`
- [n/a] Tests added
- [x ] [Changelog](CHANGELOG.md) updated
=> HTTP103 support Flink 1.20

CHANGELOG.md, src/main/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClient.java, src/main/java/com/getindata/connectors/http/internal/table/lookup/RequestFactoryBase.java, src/main/java/com/getindata/connectors/http/internal/utils/HttpHeaderUtils.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientTest.java, src/test/java/com/getindata/connectors/http/internal/table/lookup/JavaNetHttpPollingClientWithWireTest.java, src/test/java/com/getindata/connectors/http/internal/utils/HttpHeaderUtilsTest.java, src/test/resources/auth/AuthResult.json
Change the code so that the OIDC authentication flow is moved to lookup query time. This means that explain select - does not issue a network call.
Resolves http145
=> HTTP-145 SQL explain drives rest flow to OIDC endpoint.

.github/workflows/publish.yml, pom.xml
The old way of publishing artifacts is no longer supported. Central-publishing-maven-plugin is recommended now.
=> Use central-publishing-maven-plugin
